-- フィールドエディタ(field_editor)が書き出した地面のタイル。タイルの記号は res/lua/data/field_tiles.lua の定義
field = {
	cell = 1, -- 1マスの大きさ(メートル)
	width = 32,
	depth = 32,
	rows = { -- 1行がzの1列(上から z = 0、1、...)、左から x = 0、1、...
		"gggggggggggggggggggggwwwwwwwwwww",
		"ggggggggggggggggggggggwwwwwwwwww",
		"gggggggggggggggggggggggwwwwwwwww",
		"ggggggggggggggggggggggggwwwwwwww",
		"gggggggggggggggggggggggggdwwwwww",
		"gggggggggggggggggggggggggdwwwwww",
		"gggggggggggggggggggggggggddwwwww",
		"gggggggggggggggggggggggggdddwwww",
		"ggggggggggggggggggggggggggddwwww",
		"gggggssgggggggggggggggggggdddwww",
		"gggggssssggggggggggggggggggdddww",
		"gggggsssssggggggggggggggggggdddd",
		"gggggsssssssggggggggggggggggggdd",
		"gggggssssssssggggggggggggggggggd",
		"ggggggsssssssggggggggggggggggttt",
		"gggggggssssssggggggggggggggttttt",
		"gggggggggssssggggggggggggggttttt",
		"gggggggggggggsgggggggaggggtttttt",
		"gggggggggggggggggggggagggggttttt",
		"gggggggggggggggggggggagggggttttt",
		"gggggggggggggggggggggagggggttttt",
		"gggggggggggggggggggggagggggttttt",
		"gggggggggggggggggggggagggggttttt",
		"gggggggggggggggggggggaggggggtttt",
		"gggggggggggggggggggggagggggggttt",
		"gggggggggggggggggggggagggggggtgt",
		"gggggggggggggggggggggagggggggggt",
		"gggggggggggggggggggggagggggggggt",
		"gggggggggggggggggggggagggggggggt",
		"gggggggggggggggggggggagggggggggt",
		"gggggggggggggggggggggagggggggggt",
		"gggggggggggggggggggggagggggggggt",
	},
}
